---
title: "Media"
---

## Blogging

I am a maintainer and contributor to the blog **[Geekcologist: Ecology and Modelling](https://geekcologist.wordpress.com)**. In addition, I have written for a number of different media.  

- **[The domino effect of roads on biodiversity: How the impacts of wildlife-vehicle collisions propagate through food webs](https://transportecology.info/research/roadkill-cascading-effects-food-webs?fbclid=IwY2xjawLcXh1leHRuA2FlbQIxMQBicmlkETFJdnJxbWlrY0NHVnVxS2lIAR5sqWh_TjENf1mDhk-3cfksnsXRYN-rVPcVVLcjnGiN8Y6Cc1c8_f4ztrWN_g_aem_kJNC-p4_66mjlNY1V8ax0Q)**
    *Transport Ecology*. **2025**

- **[The Dynamics of the “Gentle Way”: Exploring Judo Attack Combinations as Networks in R](https://www.r-bloggers.com/2025/05/the-dynamics-of-the-gentle-way-exploring-judo-attack-combinations-as-networks-in-r/)**
    *R-bloggers*. **2025**
    
- **[Mapping research landscapes and dynamics: Some basic bibliometric analyses with R](https://www.r-bloggers.com/2025/05/mapping-research-landscapes-and-dynamics-some-basic-bibliometric-analyses-with-r/)**
    *R-bloggers*. **2025**

- **[O efeito dominó das estradas: como elas transformam as teias alimentares na natureza](https://naturaemuseubiodiv.wordpress.com/2025/03/07/o-efeito-domino-das-estradas-como-elas-transformam-as-teias-alimentares-na-natureza/?fbclid=IwY2xjawI36FZleHRuA2FlbQIxMQABHXWrQ_10Af7gC8UomwEaLVzKAaZUL3UMrj6lKHv5THUe6rv3jmEOEamz_g_aem_GA23jXCwTFp7UTvR3HOk5Q)**  
  *Naturae Digital*. **2025**.
  
- **[Estimating ecological network robustness with R: A functional approach](https://www.r-bloggers.com/2024/09/estimating-ecological-network-robustness-with-r-a-functional-approach/?fbclid=IwZXh0bgNhZW0CMTEAAR0q_4i0vXE10WFdKIU5ylnuEOUTGQKmMkcQKenOs1bvLG9i-yshfCw3d1c_aem_3IPw5i59S3Y2SWFEj_B76Q)**
    *R-bloggers*. **2024**

- **[Visualizing power models in species-area relationships using R shiny: An interactive educational tool](https://www.r-bloggers.com/2024/04/visualizing-power-models-in-species-area-relationships-using-r-shiny-an-interactive-educational-tool/)**
    *R-bloggers*. **2024**

- **[Simple and fast visualization of biodiversity occurrence data using GBIF and R shiny](https://www.r-bloggers.com/2024/04/simple-and-fast-visualization-of-biodiversity-occurrence-data-using-gbif-and-r-shiny/)**  
  *R-bloggers*. **2024**.

- **[Simulating phylogenetically structured networks](https://www.r-bloggers.com/2023/11/simulating-phylogenetically-structured-networks/)**  
  *R-bloggers*. **2023**.

- **[O “Príncipe dos Observadores” e o primeiro modelo matemático de evolução](https://naturaemuseubiodiv.wordpress.com/2023/12/13/o-principe-dos-observadores-e-o-primeiro-modelo-matematico-de-evolucao/)**  
  *Naturae Digital*. **2023**.

- **[Steps to improve connectivity consideration in EIAs for road projects](https://transportecology.info/research/connectivity-importance-in-eias)**  
  *Transport Ecology*. **2022**.

- **[Darwin to the rescue: Using phylogenetic information to overcome the Raunkiaeran Shortfall](https://www.r-bloggers.com/2021/11/darwin-to-the-rescue-using-phylogenetic-information-to-overcome-the-raunkiaeran-shortfall/)**  
  *R-bloggers*. **2021**.

- **[Reconnecting the web of life: Rewiring and network robustness](https://methodsblog.com/2019/10/21/rewiring-network-robustness-en/)**  
  *Methods in Ecology and Evolution*. **2019**.

## Media Coverage

Below, you can find some of the latest coverage in the media about our work.

### 🇬🇧

- **[The Global Water Cycle](https://www.youtube.com/watch?v=KjAPyejDtbI)**  
  *SIL International Society of Limnology*. **2025**.

- **[Heat-sensitive trees moving uphill due to rising temperatures, study finds](https://phys.org/news/2024-07-sensitive-trees-uphill-due-temperatures.html)**  
  *PhysOrg*. **2024**.
  
- **[Heat-sensitive trees move uphill seeking climate change respite](https://scienmag.com/heat-sensitive-trees-move-uphill-seeking-climate-change-respite/)**  
  *Science Magazine*. **2024**.
  
- **[Elevational shifts in tree community composition in the Brazilian Atlantic Forest related to climate change](https://vegsciblog.org/2024/07/28/elevational-shifts-in-tree-community-composition/)**  
  *Vegetetaion Science Blog*. **2024**.

- **[Heat-sensitive trees move upwards to escape rising temperatures](https://www.techexplorist.com/heat-sensitive-trees-move-upwards-escape-rising-temperatures/86436/)**  
  *Tech Explorist*. **2024**.

- **[Trees are now moving due to climate change, but it’s not the first time](https://thedebrief.org/trees-are-now-moving-due-to-climate-change-but-its-not-the-first-time/?fbclid=IwZXh0bgNhZW0CMTEAAR1uLMccB1G-qaxwzBn8uHTRGXOMSBCOMRSR0EJg-i3aIbUQyonkHZ3zn7o_aem_9DWPZ3EsGFUBCah8y29L4Q)**  
  *The Debrief*. **2024**.

- **[Trees are relocating in a race against global warming](https://www.earth.com/news/trees-are-relocating-in-a-race-against-global-warming/)**  
  *Earth.com*. **2024**.

- **[Forests in Brazil are migrating uphill to escape rising temperatures](https://interestingengineering.com/science/forests-in-brazil-are-migrating-uphill-to-escape-rising-temperatures)**  
  *Interesting Engineering*. **2024**.

- **[Brazilian Forests, Trees Literally Move to Avoid Global Warming](https://www.techtimes.com/articles/306838/20240724/brazilian-forests-trees-literally-move-avoid-global-warming.htm)**  
  *Tech Times*. **2024**.
  
### 🇵🇹  

- **[Vão-se os corais, os peixes também](https://revistapesquisa.fapesp.br/wp-content/uploads/2024/10/056-057_declinio-corais_345.pdf)**  
  *Revista FAPESP*. **2024**.

- **[Ameaça a corais brasileiros põe peixes em risco](https://revistapesquisa.fapesp.br/ameaca-a-corais-brasileiros-poe-peixes-em-risco/?fbclid=IwY2xjawGWkCRleHRuA2FlbQIxMQABHdnZTVgkA7T6Bbj0EPJ3rSaY0HsT4gprhIdfleICqgyIldaS4AskFMYDmA_aem_xj59bRLa1owbTiEWdp71pQ)**  
  *Revista FAPESP*. **2024**.

- **[Perda de 25% dos corais nos recifes brasileiros pode prejudicar até metade das espécies de peixes](https://gizmodo.uol.com.br/perda-de-25-dos-corais-nos-recifes-brasileiros-pode-prejudicar-ate-metade-das-especies-de-peixes/?fbclid=IwY2xjawGQMBlleHRuA2FlbQIxMQABHRYKnH-h8uiHG9YKwq1YNffA4Ktv75PlpcBIMVjjvTAoLFeUaf45AZ-IQQ_aem_dODZ1PC9WYuFziYzkIZChg)**  
  *Portal UOL*. **2024**.

- **[Perda de 25% dos corais nos recifes brasileiros pode prejudicar metade das espécies de peixes](https://revistagalileu.globo.com/ciencia/meio-ambiente/noticia/2024/09/perda-de-25percent-dos-corais-nos-recifes-brasileiros-pode-prejudicar-metade-das-especies-de-peixes.ghtml?utm_source=facebook&utm_medium=social&utm_campaign=post&fbclid=IwY2xjawFnKC5leHRuA2FlbQIxMQABHRANx4AnUY18ZJ0RvqV0YMaSj_GbVzuvUzbtyilnXZDR7aFrR4KiCk54mA_aem_HWTed5pmsZlv1ECMU4WBHQ)**  
  *Revista Galileu*. **2024**.
  
- **[Metade das espécies de peixes do Brasil pode ser prejudicada caso perda de recifes chegue a 25%](https://www.opovo.com.br/noticias/brasil/2024/09/30/metade-das-especies-de-peixes-do-brasil-pode-ser-prejudicada-caso-perda-de-recifes-chegue-a-25.html?fbclid=IwY2xjawFsZVdleHRuA2FlbQIxMQABHUWGuxgZ0lYf7_pDr8RhNZS14ZJH-LUxuUcTm8s4FkpLE6lcDnL6o1r0Gg_aem_7vo77Lalh9cgx_GkJwPTwg)**
  *O Povo*.**2024**.
    

- **[Perda de 25% dos corais brasileiros pode eliminar até metade das espécies de peixes](https://faunanews.com.br/perda-de-25-dos-corais-brasileiros-pode-eliminar-ate-metade-das-especies-de-peixes/?fbclid=IwY2xjawFnJ99leHRuA2FlbQIxMQABHSvQSej1DoagKam7HAbRcciG6cM6xfV87Y0HM2RrWFXwGibvT17PAJKkXg_aem_cLoE7VCD_SdpGZPEq7WCHg)**  
  *Fauna News*. **2024**.

- **[Na Mata Atlântica, árvores jovens fogem do calor](https://revistapesquisa.fapesp.br/na-mata-atlantica-arvores-jovens-fogem-do-calor/)**  
  *Revista FAPESP*. **2024**.

- **[Por que árvores da Mata Atlântica estão mudando de lugar](https://www.nexojornal.com.br/expresso/2024/08/09/por-que-arvores-da-mata-atlantica-estao-mudando-de-lugar)**  
  *Nexo*. **2024**.

- **[Árvores da mata atlântica ‘migram’ morro acima fugindo do calor, diz estudo](https://www1.folha.uol.com.br/folha-social-mais/2024/07/arvores-da-mata-atlantica-migram-morro-acima-fugindo-do-calor-diz-estudo.shtml?utm_source=twitter&utm_medium=social&utm_campaign=twfolha&s=08)**  
  *Folha de São Paulo*. **2024**.

- **[Clima mais quente faz até árvore fugir do calor, diz estudo.](https://www.estadao.com.br/ciencia/clima-arvores-calor-mata-atlantica-nprm/)**  
  *O Estado de São Paulo*. **2024**.

- **[A gangorra climática das árvores da Mata Atlântica](https://oeco.org.br/salada-verde/a-gangorra-climatica-das-arvores-da-mata-atlantica/?fbclid=IwZXh0bgNhZW0CMTEAAR1Hp-oxYDwStHj0pRMnNRBDK00dBsO3Z_VrrjkTDGMMTy96BgTZSITtn1o_aem_9WfJ1QVrUKgO8e5H-XFVQg)**  
  *O Eco*. **2024**.

- **[Árvores da mata atlântica ‘migram’ morro acima fugindo do calor, diz estudo](https://jornaldebrasilia.com.br/noticias/mundo/arvores-da-mata-atlantica-migram-morro-acima-fugindo-do-calor-diz-estudo/)**  
  *Journal de Brasília*. **2024**.

- **[Mata Atlântica: árvores estão migrando em busca de clima mais favorável](https://www.correiobraziliense.com.br/ciencia-e-saude/2024/07/6904652-mata-atlantica-arvores-estao-migrando-em-busca-de-clima-mais-favoravel.html)**  
  *Correio Braziliense*. **2024**.

- **[Mudanças climáticas: em busca de fugir do calor, árvores da Mata Atlântica estão ‘migrando’ para regiões mais altas](https://www.opovo.com.br/noticias/brasil/2024/07/24/mudancas-climaticas-em-busca-de-fugir-do-calor-arvores-da-mata-atlantica-estao-migrando-para-regioes-mais-altas.html)**  
  *O Povo*. **2024**.
  
- **[Pesquisa investiga funcionamento de ecossistemas em rios intermitentes](https://ufrn.br/imprensa/noticias/76527/pesquisa-investiga-funcionamento-de-ecossistemas-em-rios-intermitentes?fbclid=IwAR1a2RcVO0mQmtOLhT2RM3Wjozcr1WQvzQPfvfzMLInU2J4Er0Ox0rb6FpM)**  
  *UFRN*. **2023**.

### 🇪🇸 

- **[Los árboles sensibles al calor se desplazan hacia las alturas en busca de un respiro.](https://www.ecoportal.net/temas-especiales/cambio-climatico/los-arboles/)**  
  *Ecoportal*. **2024**.
