---
title: "Professional Experience"
---

## Education

- **2015**  
  PhD in Ecology | Federal University of Rio Grande do Sul, Brazil  
  *Validated by the University of Lisbon, Portugal (2019)*

- **2011**  
  Master's in Ecology | Federal University of Rio Grande do Sul, Brazil

- **2007**  
  BSc in Ecology | Catholic University of Pelotas, Brazil

## Professional Experience

- **2021-2024**  
  **Junior Researcher** | *University of Evora*, Portugal

- **2020**  
  **Post-doctoral Researcher** | *Federal University of Rio Grande do Sul - Road and Railroad Ecology center*, Brazil

- **2017-2019**  
  **Post-doctoral Researcher** | *French National Center for Scientific Research*, France

- **2016**  
  **Research Fellow** | *Federal University of Rio Grande do Sul - Laboratory of Quantitative Ecology*, Brazil

- **2013**  
  **Visiting Professor Biostatistics** | *Catholic University of Pelotas (Specialization in Conservation Biology)*, Brazil

- **2008-2009**  
  **Research Fellow** | *Catholic University of Pelotas*, Brazil

- **2008-2009**  
  **Research Fellow** | *Federal University of Rio Grande do Sul*, Brazil
  
## Member of Editorial Board

- **2023 - present**  
  **Functional Ecology** (Associate Editor)
