---
title: "Talks"
---
## Upcoming talks
- **Trait evolution and matching shape stability in ecological networks**  
  *British Ecological Society Annual Meeting*, Edinburgh, Scotland.
  
 - **Enfrentando o colapso: como a diversidade funcional e a evolução moldam a robustez das redes ecológicas**  
  *Federal University of Santa Catarina*, Florianppolis, Brazil.
  

## Past talks
- **Functional robustness of reef fish networks to simulated coral extinction: A novel analytical approach**  
  *British Ecological Society Annual Meeting*, Liverpool, England **2024**.
  
- **Coping with collapse: How functional diversity, evolutionary history, and their loss shape ecological network robustness**  
  *University of Lille*, Lille, France **2024**.

- **Cambios Climáticos: Re-enmarañando el enmarañado Darwiniano**  
  *Pedagogical and Technological University of Colombia*, Tunja, Colombia. **2023**.

- **Understanding the responses of ecological networks to global changes through the lenses of evolutionary history**  
  *Science CHANGing Policy Conference*, Evora, Portugal. **2023**.

- **Compreendendo as respostas das redes ecológicas às mudanças globais através das lentes da história evolutiva**  
  *Mediterranean Institute for Agriculture, Environment and Development - University of Evora*, Evora, Portugal. **2023**.

- **Understanding the responses of mutualistic networks to climate change through the lens of evolutionary history**  
  *Norwegian Institute for Nature Research*, Torgarden, Norway. **2022**.

- **Ecological Networks**  
  *Department of Ecology – Federal University of Rio Grande do Sul*, Porto Alegre, Brazil. **2020**.

- **Estrutura e estabilidade de redes ecológicas: Uma abordagem filogenética**  
  *Emílio Goeldi Museum*, Belém do Para, Brazil. **2020**.

- **Mundanças Climáticas: Re-embaralhando o emanharado Darwiniano**  
  *Department of Biology, Federal Institute Farroupilha*, Santa Maria, Brazil. **2020**.

- **Alterações fenológicas orientadas pelo clima e a dinâmica eco-evolutiva de redes mutualistas**  
  *Graduate Program in Animal Biology – Federal University of Pelotas*, Pelotas, Brazil. **2020**.

- **Alterações fenológicas orientadas pelo clima e a dinâmica eco-evolutiva de redes mutualistas**  
  *Department of Animal Biology – Federal University of Rio Grande do Sul*, Porto Alegre, Brazil. **2020**.

- **Functional Redundancy and the Structure and Stability of Mutualistic Networks**  
  *University of Valencia*, Valencia, Spain. **2018**.

- **Untangling the Tangled Bank: Phylogenetic- and Trait-based approaches in Network ecology**  
  *University of Lisbon*, Lisbon, Portugal. **2018**.

- **Untangling the Tangled Bank: Phylogenetic- and Trait-based approaches in Network ecology**  
  *Higher Institute of Agronomy*, Lisbon, Portugal. **2018**.
  
- **The impact of climate warming and habitat isolation on beta- diversity: lessons from experimental mesocosms**  
  *BS Climate Change Biogeography Meeting*, Evora, Portugal. **2018**.

- **Merging phylogenetic- and trait-based approaches into Network Ecology**  
  *Swansea University*, Swansea, Wales. **2017**.
  
- **The role of evolutionary modes for trait driven coextinctions in mutualistic networks**  
  *Biodiversity Theory and Modeling Research Group Meeting*, Paris, France **2017**.

- **Coextinção e robustez em redes mutualísticas: padrões e processos eco-evolutivos**  
  *Department of Ecology – Federal University of Rio Grande do Sul*, Porto Alegre, Brazil. **2016**

- **Coextinção e robustez em redes mutualísticas: padrões e processos eco-evolutivos**  
  *Department of Ecology – University of Vale dos Sinos*, São Leopoldo, Brazil. **2016**.

- **Desemaranhando o emaranhado Darwiniano: componentes ecológicos e evolutivos em redes de interação**  
  *University of São Paulo*, São Paulo, Brazil. **2016**.

- **Coextinção e robustez em redes mutualísticas**  
  *Department of Animal Biology – Federal University of Rio Grande do Sul*, Porto Alegre, Brazil. **2015**.

- **Desemaranhando o emaranhado Darwiniano: componentes ecológicos e evolutivos em redes de interação**  
  *I International Seminar of Ecological Research and Education*, Pelotas, Brazil. **2012**.

- **Detectabilidade de espécies em mastozoologia: implicações e soluções analíticas** . 
  *Econsciência Institute*, Viamão, Brazil. **2011**.

- **Considerações sobre o uso de armadilhas fotográficas na biologia da conservação**  
  *Federal University of Rio Grande do Sul/ Curicaca Institute*, Porto Alegre, Brazil. **2011**.

- **Efeitos independentes e compartilhados de área e habitat sobre a estrutura da comunidade de aves no Canal de São Gonçalo**  
  *Catholic University of Pelotas*, Pelotas, Brazil. **2010**.
