project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Bastazini Lab (WEBSITE IN PROGRESS)"

  page-footer:
    left: "&copy; Copyright 2022, Author"
    right: ""

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Research"
        href: research/index.qmd
        
      - text: "Publications"
        href: publications/index.qmd

      - text: "People"
        href: people/index.qmd

      - text: "Talks"
        href: talks/index.qmd
        
      - text: "Education"
        href: education/index.qmd

      - section: "About"
        contents:
          - text: "About me"
            href: about.qmd
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
